package com.devsoft.freshfood.data.repository

import android.content.Context
import androidx.room.withTransaction
import com.devsoft.freshfood.data.local.FreshFoodDatabase
import com.devsoft.freshfood.data.local.entity.PurchaseEntity
import com.devsoft.freshfood.data.local.entity.PurchaseItemEntity
import com.devsoft.freshfood.data.local.entity.StockBatchEntity
import com.devsoft.freshfood.data.local.entity.StockMovementEntity
import com.devsoft.freshfood.data.local.entity.SyncQueueEntity
import com.devsoft.freshfood.domain.model.PurchaseRequest
import com.devsoft.freshfood.domain.repository.PurchaseRepository
import com.devsoft.freshfood.utils.DeviceUtil
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.util.UUID

class PurchaseRepositoryImpl(
    private val database: FreshFoodDatabase,
    private val context: Context
) : PurchaseRepository {
    override suspend fun processPurchase(request: PurchaseRequest): Result<String> {
        return try {
            val purchaseId = request.id
            val createdAt = request.created_at ?: java.time.Instant.now().toString()
            val deviceId = DeviceUtil.getDeviceId(context)
            
            val purchaseEntity = PurchaseEntity(
                id = purchaseId,
                supplier_id = request.supplier_id,
                invoice_number = request.invoice_number,
                total_amount = request.total_amount,
                status = "COMPLETED",
                created_at = createdAt
            )
            
            val purchaseItems = mutableListOf<PurchaseItemEntity>()
            val stockMovements = mutableListOf<StockMovementEntity>()
            val stockBatches = mutableListOf<StockBatchEntity>()
            
            request.items.forEach { item ->
                val itemId = item.id ?: UUID.randomUUID().toString()
                val batchId = item.batch_id ?: UUID.randomUUID().toString()
                
                purchaseItems.add(
                    PurchaseItemEntity(
                        id = itemId,
                        purchase_id = purchaseId,
                        product_id = item.product_id,
                        batch_id = batchId,
                        quantity = item.quantity,
                        purchase_price = item.purchase_price,
                        expiration_date = item.expiration_date
                    )
                )
                
                stockBatches.add(
                    StockBatchEntity(
                        id = batchId,
                        product_id = item.product_id,
                        batch_number = null, // Auto-generated by backend if needed, or null
                        expiration_date = item.expiration_date,
                        quantity = item.quantity,
                        purchase_price = item.purchase_price,
                        created_at = createdAt,
                        updated_at = createdAt
                    )
                )
                
                stockMovements.add(
                    StockMovementEntity(
                        id = UUID.randomUUID().toString(),
                        product_id = item.product_id,
                        batch_id = batchId,
                        movement_type = "PURCHASE",
                        quantity = item.quantity, // Positive for IN
                        reference_id = purchaseId,
                        user_id = request.user_id,
                        created_at = createdAt
                    )
                )
            }
            
            database.withTransaction {
                database.purchaseDao().insertPurchase(purchaseEntity)
                database.purchaseDao().insertPurchaseItems(purchaseItems)
                database.stockDao().insertStockBatches(stockBatches)
                database.stockDao().insertStockMovements(stockMovements)
                
                // Update product stock locally
                request.items.forEach { item ->
                    val product = database.productDao().getProductById(item.product_id)
                    if (product != null) {
                        val newStock = product.current_stock + item.quantity
                        database.productDao().updateProduct(product.copy(current_stock = newStock))
                    }
                }
                
                // Enqueue the PurchaseRequest RPC payload for sync
                val syncQueueEntity = SyncQueueEntity(
                    entity_type = "rpc_process_purchase",
                    entity_id = purchaseId,
                    operation = "RPC",
                    payload = Json.encodeToString(request),
                    device_id = deviceId
                )
                database.syncQueueDao().insert(syncQueueEntity)
            }
            
            Result.success("PUR-${purchaseId.take(8).uppercase()}")
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
